footprint: [[-0.25, -0.25], [-0.25, 0.25], [0.25, 0.25], [0.25, -0.25]]
footprint_padding: 0.10

robot_base_frame: base_frame
update_frequency: 3.3
publish_frequency: 3.3
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 3.0
raytrace_range: 6.0

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    track_unknown_space : true
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}

inflation:
    inflation_radius: 0.40
    cost_scaling_factor: 4.0
